#!/usr/bin/env bash
# Auto-checker for helm-lab. Run after finishing: ./check.sh
PASSED=0; TOTAL=0
check() { # $1=desc $2=cmd
  TOTAL=$((TOTAL+1))
  if bash -c "$2" >/dev/null 2>&1; then echo "  PASS  $1"; PASSED=$((PASSED+1)); else echo "  FAIL  $1"; fi
}
echo "== Task 1"
check "t1-versions.txt has 3 lines" "[ \"\$(wc -l < /tmp/t1-versions.txt)\" -ge 3 ]"
echo "== Task 2"
check "t2-values.yaml exported" "grep -q 'service:' /tmp/t2-values.yaml"
echo "== Task 3"
check "frontend release, 3 replicas" "[ \"\$(kubectl -n helm-lab get deploy frontend-webapp -o jsonpath='{.spec.replicas}')\" = 3 ]"
check "configMessage set" "[ \"\$(kubectl -n helm-lab get cm frontend-webapp -o jsonpath='{.data.message}')\" = 'frontend ready' ]"
check "chart version 1.1.0" "helm list -n helm-lab | grep frontend | grep -q webapp-1.1.0"
echo "== Task 4"
check "backend svc NodePort" "[ \"\$(kubectl -n helm-lab get svc backend-webapp -o jsonpath='{.spec.type}')\" = NodePort ]"
check "backend image nginx:1.26" "[ \"\$(kubectl -n helm-lab get deploy backend-webapp -o jsonpath='{.spec.template.spec.containers[0].image}')\" = nginx:1.26 ]"
check "memory request 128Mi" "[ \"\$(kubectl -n helm-lab get deploy backend-webapp -o jsonpath='{.spec.template.spec.containers[0].resources.requests.memory}')\" = 128Mi ]"
echo "== Task 5"
check "t5-manifest.yaml has 3 kinds" "[ \"\$(grep -c '^kind:' /tmp/t5-manifest.yaml)\" = 3 ]"
check "replicas: 5" "grep -q 'replicas: 5' /tmp/t5-manifest.yaml"
check "no release created" "! helm list -A | grep -q render-test"
echo "== Task 6/7 (state after rollback)"
check "t6-old-values.yaml saved" "grep -q replicaCount /tmp/t6-old-values.yaml"
check "shop was upgraded to 1.2.0 at some point" "helm history shop -n team-a | grep -q webapp-1.2.0"
check "shop upgrade kept replicaCount=2" "helm history shop -n team-a | grep -q webapp-1.2.0 && [ \"\$(kubectl -n team-a get deploy shop-webapp -o jsonpath='{.spec.replicas}')\" = 2 ]"
check "shop rolled back to revision 1" "helm history shop -n team-a | tail -1 | grep -q 'Rollback to 1'"
check "message is shop v1" "[ \"\$(kubectl -n team-a get cm shop-webapp -o jsonpath='{.data.message}')\" = 'shop v1' ]"
echo "== Task 8"
check "broken pods Running" "[ \"\$(kubectl -n team-b get pod -l app.kubernetes.io/instance=broken --field-selector=status.phase=Running --no-headers | wc -l)\" -ge 1 ]"
check "image tag 1.25" "kubectl -n team-b get deploy broken-webapp -o jsonpath='{.spec.template.spec.containers[0].image}' | grep -q ':1.25$'"
check "fixed via helm upgrade (revision 2)" "helm history broken -n team-b | grep -q '^2 '"
echo "== Task 9"
check "t9-manual.txt = manual-app" "grep -qx manual-app /tmp/t9-manual.txt"
check "old-api uninstalled with history" "helm list -n legacy --all | grep old-api | grep -q uninstalled"
check "manual-app still exists" "kubectl -n legacy get deploy manual-app"
echo "== Task 10"
check "t10-argocd.yaml has no CRDs" "[ -f /tmp/t10-argocd.yaml ] && [ \"\$(grep -c CustomResourceDefinition /tmp/t10-argocd.yaml)\" = 0 ]"
check "argocd release exists" "helm list -n argocd -q | grep -qx argocd"
check "no argocd CRDs installed" "! kubectl get crd | grep -q argoproj.io"
echo "== Task 11"
check "webapp-v2 lint ok" "helm lint /tmp/webapp-v2"
check "chart version 2.0.0" "grep -q '^version: 2.0.0' /tmp/webapp-v2/Chart.yaml"
check "custom ingress host custom.local" "[ \"\$(kubectl -n helm-lab get ingress custom-webapp -o jsonpath='{.spec.rules[0].host}')\" = custom.local ]"
echo "== Task 12"
check "api replicas 4" "[ \"\$(kubectl -n team-b get deploy api-webapp -o jsonpath='{.spec.replicas}')\" = 4 ]"
check "api svc still NodePort" "[ \"\$(kubectl -n team-b get svc api-webapp -o jsonpath='{.spec.type}')\" = NodePort ]"
check "t12-manifest.yaml has 3 kinds" "[ \"\$(grep -c '^kind:' /tmp/t12-manifest.yaml)\" = 3 ]"
check "t12-releases.txt lists all ns" "grep -q team-a /tmp/t12-releases.txt && grep -q helm-lab /tmp/t12-releases.txt"
echo "=================================="
echo "PASSED: $PASSED / $TOTAL checks"
